name: Shipping service
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: echo mvn clean install


#       - name: Login to docker hub
#         uses: docker/login-action-@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shippingservice:latest
#
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_USERNAME }}/shippingservice:latest
#
#      - name: Push to Docker hub
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/shippingservice:latest



      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
